### PR TITLE
Update and correction of French translations

### PR DESCRIPTION
**Pull request by Devonab**
Hey, I've just downloaded your add-on on my Firefox and noticed a few small typos in the French translation. I took the opportunity to achieve it 😇 Thanks for your work.

### CODE REVIEW

**Comment by Sav22999** [comment]
Please, use Crowdin for translations

**Comment by Devonab** [comment]
Oops, my bad, I was a bit hasty reading the readme... I'm looking for Crowdin 👍

**Comment by Sav22999** [comment]
Np, thank you!

Notify me when you added translations on Crowdin so I can approve them

**Comment by Devonab** [comment]
Ready for the review 👍

**Comment by Sav22999** [comment]
@Devonab Thank you!

**Pull request closed without merging**
